### ISSUE TITLE
Hi Byran, Can you clarify the license of this code?

### ISSUE THREAD

**Issue by abramhindle** [bryanl/FakeCamera#1]
Hi Byran, Can you clarify the license of this code? I'd like to use it, but I'd really feel safer if you licensed it somehow.

Suggestions include:
- Apache2 - like BSD but more comprehensive
- GPL3 - Copyleft 

Thanks,

abram

**Comment by bryanl** [comment]
I decided to do BSD. Apache2 requires too much reading, and isn't compatible with the GPL. Hopefully this helps.
